### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SrJSDev** [ttamg/chromebook#1]
I get this error message:

```
Package libreadline-gplv2-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libreadline-gplv2-dev' has no installation candidate
```

**Comment by ttamg** [comment]
@SrJSDev Sorry I don't have that Chromebook anymore so can't investigate or make a fix if that is needed.  It is unclear to me if it is your specific machine / setup or some change in the latest ChromeOS that causes the issue more generally for others too.  

I'd be very happy for someone in the community to investigate and take over maintaining this codebase if it is useful to people.  Unfortunately I can't as I don't have a Chrome machine anymore.

**Comment by SrJSDev** [comment]
Gotcha, thanks.

FYI I noiticed that `python3` works out of the box (v3.9.2), but `python` doesn't. A simple alias may help.

**Comment by ttamg** [comment]
I'll close this issue then. @SrJSDev   Sounds like the alias is a simple solution
